### ISSUE TITLE
Feature Request: add some sort of basic auth 

### ISSUE THREAD

**Issue by mr190e** [WoozyMasta/dayz-exporter#1]
Would it be possible to add some sort of authentification? Because otherwise all data is floating freely around - not that this informations are any critical, but still it contains IP addresses and GUIDs.

**Comment by WoozyMasta** [comment]
it's not hard to do, I'll get to it somehow
but for now, if you want a solution here and now, I can suggest using a reverse proxy, for example nginx, and setting up authorization in it or allowing access to the exporter ports only from certain IPs in the firewall

**Comment by WoozyMasta** [comment]
@mr190e Although, why not now, it’s ready https://github.com/WoozyMasta/dayz-exporter/releases/tag/v0.2.0

* https://github.com/WoozyMasta/dayz-exporter?tab=readme-ov-file#authentication
* https://github.com/WoozyMasta/dayz-exporter/blob/master/cli/example.config.yaml#L8
